name: Load Testing

on:
  workflow_dispatch:

jobs:
  test_run:
    runs-on: ubuntu-latest
    environment: loadtest
    steps:
    - name: Check for ENV_NAME and AZURE_CREDENTIALS
      run: |
        if [ -z "${{ vars.ENV_NAME }}" ] || [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "ENV_NAME or AZURE_CREDENTIALS is not set in the repo settings. Please set them and try again."
          exit 1
        else
          echo "ENV_NAME is set to ${{ vars.ENV_NAME }}"
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install azd
      uses: Azure/setup-azd@v1.0.0

    - name: Get env variables from Azure Developer CLI environment
      run: |
        echo "Logging to  AZD..."
        AZURE_CREDENTIALS=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .)
        CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)
        CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)
        azd login --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --tenant-id $TENANT_ID
        echo "Getting environment variables from AZD ${{ vars.ENV_NAME }} environment..."
        export RESOURCE_GROUP_NAME=$(azd env get-values -e ${{ vars.ENV_NAME }} | grep AZURE_RESOURCE_GROUP_NAME | cut -d'=' -f2 | tr -d '"')
        echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV
        echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME"        
        export KEY_VAULT_NAME=$(azd env get-values -e ${{ vars.ENV_NAME }} | grep AZURE_KEY_VAULT_NAME | cut -d'=' -f2 | tr -d '"')
        echo "KEY_VAULT_NAME=$KEY_VAULT_NAME" >> $GITHUB_ENV
        echo "KEY_VAULT_NAME=$KEY_VAULT_NAME"
        export LOAD_TESTING_SERVICE_NAME=$(azd env get-values -e ${{ vars.ENV_NAME }} | grep AZURE_LOAD_TESTING_SERVICE_NAME | cut -d'=' -f2 | tr -d '"')
        echo "LOAD_TESTING_SERVICE_NAME=$LOAD_TESTING_SERVICE_NAME" >> $GITHUB_ENV
        echo "LOAD_TESTING_SERVICE_NAME=$LOAD_TESTING_SERVICE_NAME"        
        export ORCHESTRATOR_FUNC_NAME=$(azd env get-values -e ${{ vars.ENV_NAME }} | grep AZURE_ORCHESTRATOR_FUNC_NAME | cut -d'=' -f2 | tr -d '"')
        echo "ORCHESTRATOR_FUNC_NAME=$ORCHESTRATOR_FUNC_NAME" >> $GITHUB_ENV
        echo "ORCHESTRATOR_FUNC_NAME=$ORCHESTRATOR_FUNC_NAME"

    - name: 'Azure Load Testing'
      uses: azure/load-testing@v1
      with:
        loadTestConfigFile: 'SampleApp.yaml'
        loadTestResource: 'loadTestResourceName'
        resourceGroup: 'loadTestResourceGroup'