name: Load Testing

on:
  workflow_dispatch:

jobs:
  test_run:
    runs-on: ubuntu-latest
    environment: loadtest
    steps:
    - name: Check for ENV_NAME and AZURE_CREDENTIALS
      run: |
        if [ -z "${{ vars.AZD_ENV }}" ] || [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "AZD_ENV or AZURE_CREDENTIALS is not set in the repo settings. Please set them and try again."
          exit 1
        else
          echo "AZD_ENV is set to ${{ vars.AZD_ENV }}"
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}